//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsForSell
    {
        public ItemsForSell()
        {
            this.ItemImages = new HashSet<ItemImage>();
            this.ItemOffers = new HashSet<ItemOffer>();
            this.ItemUserBuyings = new HashSet<ItemUserBuying>();
            this.ItemUserWatchings = new HashSet<ItemUserWatching>();
            this.UserFavItems = new HashSet<UserFavItem>();
            this.Messages = new HashSet<Message>();
        }
    
        public long ItemId { get; set; }
        public long UserId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ItemCatId { get; set; }
        public double Cost { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public bool IsNegotialble { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<double> LocationLat { get; set; }
        public Nullable<double> LocationLong { get; set; }
        public bool DeliveryType { get; set; }
        public bool IsSold { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ItemCondition { get; set; }
        public string PostalCode { get; set; }
        public string PostalCodeLocation { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemCondition ItemCondition1 { get; set; }
        public virtual ICollection<ItemImage> ItemImages { get; set; }
        public virtual ICollection<ItemOffer> ItemOffers { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ItemUserBuying> ItemUserBuyings { get; set; }
        public virtual ICollection<ItemUserWatching> ItemUserWatchings { get; set; }
        public virtual ICollection<UserFavItem> UserFavItems { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
