//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public long ItemImageId { get; set; }
        public string ImagePath { get; set; }
        public long ItemId { get; set; }
        public Nullable<int> ImageOrder { get; set; }
    
        public virtual ItemsForSell ItemsForSell { get; set; }
    }
}
