//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOffer
    {
        public ItemOffer()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public long ItemOfferId { get; set; }
        public long ItemId { get; set; }
        public long UserId { get; set; }
        public double Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ItemsForSell ItemsForSell { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
