//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessgeId { get; set; }
        public long UserIdFrom { get; set; }
        public long UserIdTo { get; set; }
        public string Messge { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool IsRead { get; set; }
        public bool IsFlagged { get; set; }
        public long ItemId { get; set; }
        public Nullable<long> ItemOfferId { get; set; }
    
        public virtual ItemOffer ItemOffer { get; set; }
        public virtual ItemsForSell ItemsForSell { get; set; }
        public virtual User User { get; set; }
    }
}
