//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long UserDetailsId { get; set; }
        public string DisplayName { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> LocationLat { get; set; }
        public Nullable<decimal> LocationLong { get; set; }
        public string LocationName { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> Rating { get; set; }
        public System.DateTime JoinedDate { get; set; }
        public int UserType { get; set; }
        public long UserId { get; set; }
        public string ProfileImagePath { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserType UserType1 { get; set; }
    }
}
