//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ItemOffers = new HashSet<ItemOffer>();
            this.ItemsForSells = new HashSet<ItemsForSell>();
            this.ItemUserBuyings = new HashSet<ItemUserBuying>();
            this.ItemUserWatchings = new HashSet<ItemUserWatching>();
            this.UserDetails = new HashSet<UserDetail>();
            this.UserFavItems = new HashSet<UserFavItem>();
            this.Messages = new HashSet<Message>();
        }
    
        public long UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<ItemOffer> ItemOffers { get; set; }
        public virtual ICollection<ItemsForSell> ItemsForSells { get; set; }
        public virtual ICollection<ItemUserBuying> ItemUserBuyings { get; set; }
        public virtual ICollection<ItemUserWatching> ItemUserWatchings { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<UserFavItem> UserFavItems { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
